model:
  name: "sycle_gan"

trainer: 
  n_residual_blocks : 9
  lr : 0.0002
  b1 : 0.5
  b2 : 0.999
  n_epochs : 400
  init_epoch : 0
  decay_epoch : 100
  lambda_cyc : 10
  lambda_id : 5
  n_cpu : 8
  batch_size : 8
  sample_interval : 100
  checkpoint_interval : 5 

data:
  name : "resize_and_padding3" 
  channels: 3
  img_height : 256
  img_width : 256
  